---
- name: Install Docker and Python 3.11
  hosts: "{{ target_hosts | default('localhost') }}"
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    # Step 2: Install prerequisites for Python 3.11
    - name: Install prerequisites for Python 3.11
      apt:
        name:
          - software-properties-common
          - apt-transport-https
          - ca-certificates
        state: present

    # Step 3: Add Python 3.11 repository
    - name: Add Python 3.11 repository
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present

    # Step 4: Install Python 3.11
    - name: Install Python 3.11
      apt:
        name: python3.11
        state: present

    - name: Install pip for Python 3.11
      apt:
        name: python3.11-venv
        state: present

    - name: Install python3.11-pip
      apt:
        name: python3.11-pip
        state: present

    # Step 5: Verify Python 3.11 installation
    - name: Verify Python 3.11 installation
      command: python3.11 --version
      register: python_version

    - name: Show Python version
      debug:
        var: python_version.stdout
