---
- name: Deploy RabbitMQ using Docker on macOS
  hosts: "{{ target_hosts | default('localhost') }}"
  become: yes
  tasks:

    - name: Ensure Docker Desktop is installed
      homebrew_cask:
        name: docker
        state: present

    # Важно: После установки Docker Desktop на macOS необходимо запустить его вручную
    # или автоматизировать запуск приложения. Без запущенного Docker Desktop
    # последующие задачи с docker_* модулями не будут работать.

    - name: Pull the official RabbitMQ Docker image
      docker_image:
        name: rabbitmq
        source: pull

    - name: Run RabbitMQ container
      docker_container:
        name: rabbitmq
        image: rabbitmq
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "5672:5672"
          - "15672:15672"
        env:
          RABBITMQ_DEFAULT_USER: "user"
          RABBITMQ_DEFAULT_PASS: "password"
        volumes:
          - "rabbitmq_data:/var/lib/rabbitmq"

    - name: Check RabbitMQ container status
      docker_container_info:
        name: rabbitmq
      register: rabbitmq_info

    - name: Show RabbitMQ container status
      debug:
        var: rabbitmq_info